#version: '3.8'
#
#services:
#  postgres:
#    image: postgres:13-alpine
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: Pxhd4850
#      POSTGRES_DB: health
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#
#
#volumes:
#  postgres-data: